// import Head from 'next/head'
// import Image from 'next/image'
// import { Inter } from 'next/font/google'
// import styles from '@/styles/Home.module.css'



// export default function Home() {
//   return (
//     <>
//       <Head>
//         <title>Create Next App</title>
//         <meta name="description" content="Generated by create next app" />
//         <meta name="viewport" content="width=device-width, initial-scale=1" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>
//       <main className={styles.main}>
//        <div>
//          index
         
//        </div>
       
        
//       </main>
//     </>
//   )
// }


import React from 'react'
import { Products, FooterBanner, HeroBanner} from '../components/index'
import { client } from '@/components/lib/client'


const Home = ({ product, bannerData }) =>  {
  
  return (
    <>
     <HeroBanner heroBanner={bannerData.length && bannerData[0]} />
     {/* {console.log(bannerData)} */}
    <div className='products-heading'>
      <h2>Best Selling products</h2>
      <p>Speaker of many variations</p>
    </div>
    <div className='products-container'> 
     {product?.map((product) => <Products key={product._id} product={product} />)}
      {console.log(product)}
    </div>
     
      <FooterBanner footerBanner={bannerData &&  bannerData[0]}/>
    </>
  );
  }
  export const getServerSideProps = async () => {
    const query = '*[_type == "product"]';
    const product = await client.fetch(query);

    const bannerQuery = '*[_type == "banner"]';
    const bannerData = await client.fetch(bannerQuery);

    return {
      props: { product, bannerData}
    }
    
  }

export default Home
